### PR TITLE
Added Origin Check Feature

### PR DESCRIPTION
**Pull request by arunoda**
Implement the origin check feature discussed in the issue #44

### CODE REVIEW

**Comment by rauchg** [comment]
No tests make websocket.io a dull boy

**Comment by arunoda** [comment]
Yes I know. But I haven't used mocha :) 
Have to learn it

**Comment by arunoda** [comment]
Tests added.
Any idea on how to create a WS Client with origin header? 
The current used on does not create a header since it is not a browser client.

**Comment by rauchg** [comment]
@einaros is it possible to do this with the `ws` client?

**Comment by rauchg** [comment]
Thanks for your help @arunoda btw

**Comment by arunoda** [comment]
NP.

**Comment by einaros** [comment]
This is already available with ws, although you would do it in a custom connection verification callback passed to the websocket server constructor, not with an origin config option.

**Comment by arunoda** [comment]
I tried origin option. But it didn't work. appreciate your help. But I really didn't get this **custom connection verification callback**

Hope someone can show me an example :)

**Comment by einaros** [comment]
It works very well, otherwise the tests would fail :)

See tests/WebSocketServer.test.js and search for 'origin'.

**Comment by arunoda** [comment]
Thanks :)

**Comment by arunoda** [comment]
Got it. Its via plain HTTP. I simply forgot it :)

**Comment by einaros** [comment]
This is what I get from not reading the actual issue discussion. I was talking about functionality to filter connection attempts based on origin. _That_ is already in ws.

As for `origin` for ws clients, that's the `origin` option as you've probably already noticed.

**Comment by arunoda** [comment]
okay. I just noticed that. seems its synchronous? 
We suggests an asynchronous one?

see #44

BTW: i'm new to this, seems like websockets.io using ws internally.
@guille what is the difference between websockets.io and ws

**Comment by arunoda** [comment]
I just read the source, seems like it has support for both synchronous and asynchronous

**Comment by rauchg** [comment]
@arunoda seeing as ws has added support for older drafts now, I won't be adding new features to websocket.io for the moment. Please look at ws if you need to do origin filtering. Thanks again, sorry for not having spotted that

**Comment by arunoda** [comment]
That's okay. ws sound great to me.
Thanks.

**Pull request closed without merging**
